[package]
name = "assumevalid"
version = "0.1.0"
edition = "2024_07"

[executable]

[dependencies]
cairo_execute = "2.11.4"
consensus = { path = "../consensus" }
utils = { path = "../utils" }
stwo_cairo_air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "67741af89e5830cdd9ae55c0824a54be6b1967d9" }

[features]
qm31_opcode = ["stwo_cairo_air/qm31_opcode"]

[dev-dependencies]
cairo_test.workspace = true
