[package]
name = "assumevalid"
version = "0.1.0"
edition = "2024_07"

[executable]
allow-syscalls=true

[dependencies]
cairo_execute = "2.11.4"
consensus = { path = "../consensus" }
utils = { path = "../utils" }
stwo_cairo_air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "27b07f51bf3da3b4eebd01f3ecb43290cd497671", features = ["qm31_opcode"] }

[features]
default = ["syscalls"]
syscalls = ["consensus/syscalls", "utils/syscalls"]

[dev-dependencies]
cairo_test.workspace = true
