[package]
name = "stone_wrapper"
version = "0.1.0"
edition = "2024_07"

[executable]

[dependencies]
cairo_execute = "2.12.0"
stwo_cairo_air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "c273eed286f20681d9e94aa7a7125b8fea8d7a85", default-features = false, features = ["poseidon252_verifier"] }

[cairo]
enable-gas = false
