[package]
name = "raito-spv-client"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core SPV functionality
raito-spv-core = { path = "../raito-spv-core" }

# Bitcoin RPC and types
bitcoin.workspace = true

# CLI and env
clap = { workspace = true }
dotenv = { workspace = true }

# Async runtime
tokio = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
